services:
  rust-backend:
    image: ghcr.io/squad-mandalore/ttbackend:latest
    ports:
      - 8080:3000
    environment:
      - DATABASE_URL=postgres://postgres:${POSTGRES_PASSWORD}@database:5432/ttbackend
    depends_on:
      - database

  database:
    image: postgres:16.4
    restart: always
    environment:
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
