services:
  rust-backend:
    image: ghcr.io/squad-mandalore/ttbackend:latest
    ports:
      - 8080:3000
    environment:
      - DATABASE_URL=postgres://postgres:${POSTGRES_PASSWORD}@database:5432/ttbackend
      - JWT_SECRET=${JWT_SECRET}
      - PEPPER=${PEPPER}
      - SALT_LENGTH=${SALT_LENGTH}
      - KEYCHAIN_NUMBER=${KEYCHAIN_NUMBER}
    depends_on:
      - database

  database:
    image: postgres:16.4
    restart: always
    environment:
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
